spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
server:
  port: 9999
  servlet:
    context-path: /api
metric:
  url: http://localhost:8888
  checkRange: 300
  workers: 100
http-client:
  connect-timeout: 1000
  connect-request-timeout: 1000
  keep-alive-time: 5000
  read-timeout: 1000
  buffer-requestBody: true
  max-pool-size: 100
  connection-TTL: 1000